version: '3'

services:
  nucklear_it_hack:
    # Указываем путь к Dockerfile
    build: .
    # Задаем имя будущего контейнера
    container_name: nucklear_it_hack
    # Включаем автоматический перезапуск в случае возникновения ошибок
    restart: on-failure
    # Пробрасываем 8000 порт из контейнера в 5000 порт хоста
    ports:
      - "127.0.0.1:8000:8000"